import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabaseClient';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ChevronRight, DollarSign, TrendingUp, Lock,
  Unlock, Shield, Download, Search, Filter,
  X, Check, AlertCircle, Calendar, Briefcase,
  ArrowUpRight, ArrowDownLeft, Clock, CreditCard,
  Plus, Eye, RefreshCw, CheckCircle, Zap,
  Building, FileText, ChevronDown, Users,
  IndianRupee, Wallet, BarChart2, Target,
  LayoutDashboard, Bell, Settings, ShieldCheck,
  ChevronLeft, ArrowLeft
} from 'lucide-react';

const Payments = () => {
  const navigate = useNavigate();

  // Authentication Guard
  useEffect(() => {
    const checkAuth = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        navigate('/signin?role=company');
      }
    };
    checkAuth();

    const { data: authListener } = supabase.auth.onAuthStateChange((event, session) => {
      if (!session) {
        navigate('/signin?role=company');
      }
    });

    return () => {
      if (authListener?.subscription) {
        authListener.subscription.unsubscribe();
      }
    };
  }, [navigate]);

  const [activeTab, setActiveTab] = useState('Overview');
  const [searchQuery, setSearchQuery] = useState('');
  const [filterStatus, setFilterStatus] = useState('All');
  const [showAddFundsModal, setShowAddFundsModal] = useState(false);
  const [showReleaseModal, setShowReleaseModal] = useState(null);
  const [showInvoiceModal, setShowInvoiceModal] = useState(null);
  const [selectedAmount, setSelectedAmount] = useState('');
  const [customAmount, setCustomAmount] = useState('');
  const [paymentMethod, setPaymentMethod] = useState('upi');
  const [addFundsSent, setAddFundsSent] = useState(false);
  const [releaseSent, setReleaseSent] = useState(false);

  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [showNotifications, setShowNotifications] = useState(false);

  const navItems = [
    { icon: LayoutDashboard, label: 'Dashboard', path: '/company-dashboard' },
    { icon: FileText, label: 'My Requirements', path: '/requirements' },
    { icon: Users, label: 'Experts', path: '/experts' },
    { icon: CreditCard, label: 'Payments', path: '/payments', active: true },
    { icon: BarChart2, label: 'Analytics', path: '/analytics' },
    { icon: ShieldCheck, label: 'PMO Services', path: '/pmo' },
    { icon: Settings, label: 'Settings', path: '/settings' },
  ];

  const notifications = [
    { id: 1, title: 'Milestone Payment Pending', desc: 'Investor Deck & Data Room awaits payment release', time: '2 min ago', unread: true, color: 'bg-amber-500' },
    { id: 2, title: 'Funds Added Successfully', desc: '₹9,00,000 added to Go-to-Market Expansion escrow', time: '2 days ago', unread: true, color: 'bg-emerald-500' },
    { id: 3, title: 'Invoice Generated', desc: 'INV-2025-004 generated for Investor Deck milestone', time: '3 days ago', unread: false, color: 'bg-blue-500' },
  ];
  const unreadCount = notifications.filter(n => n.unread).length;

  // Add functional handlers:
  const handleExportCSV = () => {
    const csvContent = [
      ['Transaction ID', 'Description', 'Engagement', 'Expert', 'Amount', 'Date', 'Status', 'Method'],
      ...transactions.map(tx => [tx.txRef, tx.description, tx.engagement, tx.expert, tx.amount, tx.date, tx.status, tx.method])
    ].map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'CXOConnect_Transactions.csv';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadStatement = () => {
    const content = `CXO CONNECT — PAYMENT STATEMENT\n${'='.repeat(40)}\n\nTotal Escrow Balance: ${escrowSummary.totalBalance}\nTotal Released: ${escrowSummary.totalSpent}\nPending Release: ${escrowSummary.pendingRelease}\nTotal Committed: ${escrowSummary.totalEngagementValue}\n\n${'='.repeat(40)}\nTRANSACTIONS\n${'='.repeat(40)}\n\n${transactions.map(tx => `${tx.date} | ${tx.txRef} | ${tx.description} | ${tx.amount} | ${tx.status}`).join('\n')}\n\n${'='.repeat(40)}\nGenerated by CXO Connect on ${new Date().toLocaleDateString()}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'CXOConnect_Statement.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadInvoice = (invoice) => {
    const content = `INVOICE\n${'='.repeat(40)}\nInvoice No: ${invoice.id}\nTitle: ${invoice.title}\nExpert: ${invoice.expert}\nEngagement: ${invoice.engagement}\nType: ${invoice.type}\nDate: ${invoice.date}\nDue: ${invoice.dueDate}\nStatus: ${invoice.status}\n\nAMOUNT: ${invoice.amount}\n\n${'='.repeat(40)}\nGenerated by CXO Connect Platform`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${invoice.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabs = ['Overview', 'Transactions', 'Invoices', 'Escrow'];

  // ── DATA ──
  const escrowSummary = {
    totalBalance: '₹6,00,000',
    totalBalanceNum: 600000,
    totalSpent: '₹9,00,000',
    totalSpentNum: 900000,
    pendingRelease: '₹2,50,000',
    pendingReleaseNum: 250000,
    totalEngagementValue: '₹18,00,000',
  };

  const escrowAccounts = [
    {
      id: 1,
      engagement: 'Series B Funding Strategy',
      expert: 'David Chen',
      expertAvatar: 'https://i.pravatar.cc/150?u=david',
      balance: '₹2,50,000',
      balanceNum: 250000,
      status: 'Active',
      pendingMilestone: 'Investor Deck & Data Room',
      totalValue: '₹18,00,000',
      released: '₹3,50,000',
    },
    {
      id: 2,
      engagement: 'Go-to-Market Expansion',
      expert: 'Sarah Jenkins',
      expertAvatar: 'https://i.pravatar.cc/150?u=sarah',
      balance: '₹3,50,000',
      balanceNum: 350000,
      status: 'Active',
      pendingMilestone: 'Campaign Launch',
      totalValue: '₹9,00,000',
      released: '₹5,50,000',
    },
  ];

  const transactions = [
    {
      id: 'TXN-005-2025',
      type: 'milestone_release',
      description: 'Milestone Payment — Financial Model Development',
      engagement: 'Series B Funding Strategy',
      expert: 'David Chen',
      expertAvatar: 'https://i.pravatar.cc/150?u=david',
      amount: '-₹2,00,000',
      amountNum: -200000,
      date: 'Mar 28, 2025',
      time: '3:45 PM',
      status: 'Completed',
      method: 'Escrow Release',
      txRef: 'TXN-005-2025',
    },
    {
      id: 'TXN-004-2025',
      type: 'escrow_add',
      description: 'Funds Added to Escrow',
      engagement: 'Go-to-Market Expansion',
      expert: 'Sarah Jenkins',
      expertAvatar: 'https://i.pravatar.cc/150?u=sarah',
      amount: '+₹9,00,000',
      amountNum: 900000,
      date: 'Feb 27, 2025',
      time: '11:20 AM',
      status: 'Completed',
      method: 'Net Banking',
      txRef: 'TXN-004-2025',
    },
    {
      id: 'TXN-003-2025',
      type: 'milestone_release',
      description: 'Milestone Payment — Discovery & Assessment',
      engagement: 'Series B Funding Strategy',
      expert: 'David Chen',
      expertAvatar: 'https://i.pravatar.cc/150?u=david',
      amount: '-₹1,50,000',
      amountNum: -150000,
      date: 'Feb 25, 2025',
      time: '5:00 PM',
      status: 'Completed',
      method: 'Escrow Release',
      txRef: 'TXN-003-2025',
    },
    {
      id: 'TXN-002-2025',
      type: 'escrow_add',
      description: 'Funds Added to Escrow',
      engagement: 'Series B Funding Strategy',
      expert: 'David Chen',
      expertAvatar: 'https://i.pravatar.cc/150?u=david',
      amount: '+₹18,00,000',
      amountNum: 1800000,
      date: 'Feb 1, 2025',
      time: '10:00 AM',
      status: 'Completed',
      method: 'NEFT',
      txRef: 'TXN-002-2025',
    },
    {
      id: 'TXN-001-2025',
      type: 'platform_fee',
      description: 'Platform Fee — Engagement Setup',
      engagement: 'Series B Funding Strategy',
      expert: '—',
      expertAvatar: null,
      amount: '-₹27,000',
      amountNum: -27000,
      date: 'Feb 1, 2025',
      time: '10:05 AM',
      status: 'Completed',
      method: 'Auto-debit',
      txRef: 'TXN-001-2025',
    },
    {
      id: 'TXN-006-2025',
      type: 'milestone_release',
      description: 'Milestone Payment — Campaign Strategy',
      engagement: 'Go-to-Market Expansion',
      expert: 'Sarah Jenkins',
      expertAvatar: 'https://i.pravatar.cc/150?u=sarah',
      amount: '-₹1,50,000',
      amountNum: -150000,
      date: 'Apr 1, 2025',
      time: '2:30 PM',
      status: 'Completed',
      method: 'Escrow Release',
      txRef: 'TXN-006-2025',
    },
    {
      id: 'TXN-007-2025',
      type: 'milestone_release',
      description: 'Milestone Payment — Pending Approval',
      engagement: 'Series B Funding Strategy',
      expert: 'David Chen',
      expertAvatar: 'https://i.pravatar.cc/150?u=david',
      amount: '-₹2,50,000',
      amountNum: -250000,
      date: '—',
      time: '—',
      status: 'Pending',
      method: 'Escrow Release',
      txRef: 'TXN-007-2025',
    },
  ];

  const invoices = [
    {
      id: 'INV-2025-006',
      title: 'March 2025 — Financial Model Development',
      engagement: 'Series B Funding Strategy',
      expert: 'David Chen',
      expertAvatar: 'https://i.pravatar.cc/150?u=david',
      amount: '₹2,00,000',
      date: 'Mar 28, 2025',
      dueDate: 'Mar 28, 2025',
      status: 'Paid',
      type: 'Milestone Invoice',
    },
    {
      id: 'INV-2025-005',
      title: 'Campaign Strategy Completion',
      engagement: 'Go-to-Market Expansion',
      expert: 'Sarah Jenkins',
      expertAvatar: 'https://i.pravatar.cc/150?u=sarah',
      amount: '₹1,50,000',
      date: 'Apr 1, 2025',
      dueDate: 'Apr 1, 2025',
      status: 'Paid',
      type: 'Milestone Invoice',
    },
    {
      id: 'INV-2025-004',
      title: 'Investor Deck & Data Room',
      engagement: 'Series B Funding Strategy',
      expert: 'David Chen',
      expertAvatar: 'https://i.pravatar.cc/150?u=david',
      amount: '₹2,50,000',
      date: 'Apr 25, 2025',
      dueDate: 'May 5, 2025',
      status: 'Pending',
      type: 'Milestone Invoice',
    },
    {
      id: 'INV-2025-003',
      title: 'Platform Service Fee — Q1 2025',
      engagement: 'All Engagements',
      expert: 'CXO Connect',
      expertAvatar: null,
      amount: '₹27,000',
      date: 'Feb 1, 2025',
      dueDate: 'Feb 1, 2025',
      status: 'Paid',
      type: 'Platform Fee',
    },
    {
      id: 'INV-2025-002',
      title: 'February 2025 — Discovery & Assessment',
      engagement: 'Series B Funding Strategy',
      expert: 'David Chen',
      expertAvatar: 'https://i.pravatar.cc/150?u=david',
      amount: '₹1,50,000',
      date: 'Feb 25, 2025',
      dueDate: 'Feb 25, 2025',
      status: 'Paid',
      type: 'Milestone Invoice',
    },
  ];

  const quickAmounts = ['₹1,0,000', '₹2,50,000', '₹5,0,000', '₹10,00,000'];
  const paymentMethods = [
    { id: 'upi', label: 'UPI', icon: '🔵', desc: 'Instant transfer' },
    { id: 'neft', label: 'NEFT / IMPS', icon: '🏦', desc: '2-4 hours' },
    { id: 'netsbanking', label: 'Net Banking', icon: '💻', desc: 'Instant' },
    { id: 'card', label: 'Credit / Debit Card', icon: '💳', desc: '+ 2% fee' },
  ];

  // ── HELPERS ──
  const getStatusStyle = (status) => {
    switch (status) {
      case 'Completed': return 'text-emerald-600 bg-emerald-50 border-emerald-200';
      case 'Pending': return 'text-amber-600 bg-amber-50 border-amber-200';
      case 'Failed': return 'text-red-600 bg-red-50 border-red-200';
      case 'Paid': return 'text-emerald-600 bg-emerald-50 border-emerald-200';
      default: return 'text-gray-400 bg-gray-50 border-gray-200';
    }
  };

  const getTxIcon = (type) => {
    switch (type) {
      case 'milestone_release': return { icon: Unlock, color: 'text-red-500', bg: 'bg-red-50' };
      case 'escrow_add': return { icon: Plus, color: 'text-emerald-500', bg: 'bg-emerald-50' };
      case 'platform_fee': return { icon: Shield, color: 'text-purple-500', bg: 'bg-purple-50' };
      default: return { icon: DollarSign, color: 'text-gray-400', bg: 'bg-gray-50' };
    }
  };

  const filteredTransactions = transactions.filter(tx => {
    const matchSearch = tx.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      tx.engagement.toLowerCase().includes(searchQuery.toLowerCase()) ||
      tx.expert.toLowerCase().includes(searchQuery.toLowerCase());
    const matchFilter = filterStatus === 'All' || tx.status === filterStatus;
    return matchSearch && matchFilter;
  });

  const handleAddFunds = () => {
    setAddFundsSent(true);
    setTimeout(() => {
      setShowAddFundsModal(false);
      setAddFundsSent(false);
      setSelectedAmount('');
      setCustomAmount('');
      setPaymentMethod('upi');
    }, 2000);
  };

  const handleRelease = () => {
    setReleaseSent(true);
    setTimeout(() => {
      setShowReleaseModal(null);
      setReleaseSent(false);
    }, 2000);
  };

  return (
  <div className="min-h-screen bg-[#f4f7f5]">

    {/* ── SIDEBAR ── */}
    <motion.aside
      initial={{ width: 260 }}
      animate={{ width: isSidebarOpen ? 260 : 68 }}
      transition={{ duration: 0.3, ease: [0.4, 0, 0.2, 1] }}
      className="bg-white border-r border-gray-100 flex flex-col z-50 overflow-hidden shrink-0 shadow-sm fixed left-0 top-0 h-screen"
    >
      <div className="flex items-center gap-3 px-4 py-4 border-b border-gray-50">
        <div className="w-9 h-9 bg-[#134e40] rounded-xl flex items-center justify-center shrink-0">
          <span className="text-white font-black text-sm">C</span>
        </div>
        <motion.div
          animate={{ opacity: isSidebarOpen ? 1 : 0, width: isSidebarOpen ? 'auto' : 0 }}
          transition={{ duration: 0.2 }}
          className="overflow-hidden whitespace-nowrap"
        >
          <p className="text-[#134e40] font-black text-sm leading-none">CXO Connect</p>
          <p className="text-gray-400 text-[10px] mt-0.5">Company Portal</p>
        </motion.div>
        <motion.button
          animate={{ marginLeft: isSidebarOpen ? 'auto' : 0 }}
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          onClick={() => setIsSidebarOpen(!isSidebarOpen)}
          className="w-7 h-7 rounded-lg bg-gray-50 flex items-center justify-center text-gray-400 hover:text-[#134e40] hover:bg-gray-100 transition-all shrink-0"
        >
          {isSidebarOpen ? <ChevronLeft size={14} /> : <ChevronRight size={14} />}
        </motion.button>
      </div>

      <nav className="flex-1 px-3 py-2 space-y-0.5 overflow-hidden">
        {isSidebarOpen && (
          <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest px-2 mb-2">Main Menu</p>
        )}
        {navItems.map((item) => (
          <motion.button
            key={item.path}
            whileHover={{ x: 2, transition: { duration: 0.15 } }}
            whileTap={{ scale: 0.97 }}
            onClick={() => navigate(item.path)}
            className={`w-full flex items-center gap-3 px-3 py-2 rounded-xl transition-all duration-150 relative ${
              item.active
                ? 'bg-[#134e40] text-white shadow-md'
                : 'text-gray-500 hover:bg-gray-50 hover:text-[#134e40]'
            }`}
          >
            {item.active && (
              <motion.div
                layoutId="activeNavPayments"
                className="absolute left-0 top-1 bottom-1 w-0.5 bg-[#0eb59a] rounded-r-full"
              />
            )}
            <item.icon size={17} className="shrink-0" />
            <motion.span
              animate={{ opacity: isSidebarOpen ? 1 : 0, width: isSidebarOpen ? 'auto' : 0 }}
              transition={{ duration: 0.2 }}
              className="overflow-hidden whitespace-nowrap text-sm font-bold"
            >
              {item.label}
            </motion.span>
          </motion.button>
        ))}
      </nav>
    </motion.aside>

    {/* ── MAIN CONTENT ── */}
    <div
      className="flex flex-col min-h-screen overflow-x-hidden"
      style={{
        marginLeft: isSidebarOpen ? 260 : 68,
        transition: 'margin-left 0.3s cubic-bezier(0.4,0,0.2,1)',
      }}
    >

      {/* ── TOP HEADER ── */}
      <header className="sticky top-0 z-30 bg-white border-b border-gray-100 shadow-sm px-6 py-3 flex items-center gap-4">
        <div className="flex items-center gap-1.5 text-xs text-gray-400 flex-1">
          <button onClick={() => navigate('/company-dashboard')} className="hover:text-[#134e40] font-semibold transition-colors">Dashboard</button>
          <ChevronRight size={12} className="text-gray-300" />
          <span className="text-[#134e40] font-bold">Payments & Escrow</span>
        </div>

        <div className="flex items-center gap-3">
          {/* Export */}
          <motion.button
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={handleExportCSV}
            className="hidden md:flex items-center gap-2 px-3 py-2 bg-gray-50 border border-gray-200 text-gray-600 text-xs font-bold rounded-xl hover:bg-gray-100 transition-all"
          >
            <Download size={13} /> Export
          </motion.button>

          {/* Add Funds */}
          <motion.button
            whileHover={{ scale: 1.04, boxShadow: '0 8px 25px rgba(20,78,64,0.3)' }}
            whileTap={{ scale: 0.96 }}
            onClick={() => setShowAddFundsModal(true)}
            className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-[#134e40] to-[#0eb59a] text-white text-xs font-black rounded-xl shadow-md"
          >
            <Plus size={13} /> Add Funds
          </motion.button>

          {/* Bell */}
          <div className="relative">
            <motion.button
              whileHover={{ scale: 1.08 }}
              whileTap={{ scale: 0.92 }}
              onClick={() => setShowNotifications(!showNotifications)}
              className="w-9 h-9 bg-gray-50 rounded-xl flex items-center justify-center text-gray-500 hover:text-[#134e40] hover:bg-gray-100 transition-all relative"
            >
              <Bell size={17} />
              {unreadCount > 0 && (
                <motion.span
                  animate={{ scale: [1, 1.2, 1] }}
                  transition={{ duration: 2, repeat: Infinity }}
                  className="absolute -top-0.5 -right-0.5 w-4 h-4 bg-red-500 text-white text-[9px] font-black rounded-full flex items-center justify-center"
                >
                  {unreadCount}
                </motion.span>
              )}
            </motion.button>

            <AnimatePresence>
              {showNotifications && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setShowNotifications(false)} />
                  <motion.div
                    initial={{ opacity: 0, y: -8, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: -8, scale: 0.95 }}
                    transition={{ duration: 0.2 }}
                    className="absolute right-0 top-11 w-80 bg-white rounded-2xl shadow-2xl border border-gray-100 z-50 overflow-hidden"
                  >
                    <div className="flex items-center justify-between px-4 py-3 border-b border-gray-50">
                      <h4 className="font-black text-[#1C3627] text-sm">Notifications</h4>
                      <span className="text-[10px] font-bold text-[#0eb59a] cursor-pointer">Mark all read</span>
                    </div>
                    {notifications.map((notif, idx) => (
                      <motion.div
                        key={notif.id}
                        initial={{ opacity: 0, x: -8 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: idx * 0.05 }}
                        className={`flex items-start gap-3 px-4 py-3 cursor-pointer border-b border-gray-50 last:border-0 hover:bg-gray-50 transition-colors ${notif.unread ? 'bg-teal-50/20' : ''}`}
                      >
                        <div className={`w-8 h-8 ${notif.color} rounded-xl flex items-center justify-center shrink-0`}>
                          <Bell size={13} className="text-white" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-xs font-black text-[#1C3627] mb-0.5 text-left">{notif.title}</p>
                          <p className="text-[11px] text-gray-500 text-left">{notif.desc}</p>
                          <p className="text-[10px] text-gray-400 mt-1 text-left">{notif.time}</p>
                        </div>
                        {notif.unread && <div className="w-2 h-2 bg-[#0eb59a] rounded-full shrink-0 mt-1" />}
                      </motion.div>
                    ))}
                    <div className="px-4 py-3 border-t border-gray-50 text-center">
                      <button className="text-xs font-bold text-[#0eb59a] hover:text-[#134e40] transition-colors">View all notifications →</button>
                    </div>
                  </motion.div>
                </>
              )}
            </AnimatePresence>
          </div>

          <button className="w-9 h-9 bg-[#134e40] rounded-xl flex items-center justify-center text-white text-xs font-black hover:ring-2 hover:ring-[#0eb59a] hover:ring-offset-2 transition-all">
            AC
          </button>
        </div>
      </header>

      {/* ── PAGE BODY ── */}
      <div className="flex-1 px-6 py-5 pb-16 space-y-5 overflow-x-hidden">

        {/* ── KPI CARDS ── */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
          {[
            { label: 'Escrow Balance', value: escrowSummary.totalBalance, icon: Wallet, iconBg: 'bg-teal-50', iconColor: 'text-[#0eb59a]', numColor: 'text-[#134e40]', border: 'border-l-[#0eb59a]', sub: 'Secured funds' },
            { label: 'Total Released', value: escrowSummary.totalSpent, icon: Unlock, iconBg: 'bg-emerald-50', iconColor: 'text-emerald-500', numColor: 'text-emerald-700', border: 'border-l-emerald-400', sub: '4 milestones paid' },
            { label: 'Pending Release', value: escrowSummary.pendingRelease, icon: Clock, iconBg: 'bg-amber-50', iconColor: 'text-amber-500', numColor: 'text-amber-700', border: 'border-l-amber-400', sub: 'Awaiting approval' },
            { label: 'Total Committed', value: escrowSummary.totalEngagementValue, icon: Target, iconBg: 'bg-purple-50', iconColor: 'text-purple-500', numColor: 'text-purple-700', border: 'border-l-purple-400', sub: '2 engagements' },
          ].map((card, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.07 }}
              whileHover={{ y: -4, boxShadow: '0 12px 30px rgba(0,0,0,0.08)', transition: { duration: 0.2 } }}
              style={{ boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}
              className={`bg-white rounded-2xl p-4 border-l-4 ${card.border} cursor-default`}
            >
              <div className="flex items-center gap-2 mb-2">
                <div className={`w-6 h-6 ${card.iconBg} rounded-md flex items-center justify-center shrink-0`}>
                  <card.icon size={12} className={card.iconColor} />
                </div>
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest text-left">{card.label}</span>
              </div>
              <p className={`text-[22px] font-black ${card.numColor} tracking-tight leading-none text-left mb-1`}>{card.value}</p>
              <p className="text-[10px] text-gray-400 font-medium text-left">{card.sub}</p>
            </motion.div>
          ))}
        </div>

        {/* ── TABS ── */}
        <div className="flex gap-1 bg-white rounded-2xl p-1 w-fit" style={{ boxShadow: '0 2px 8px rgba(0,0,0,0.04)' }}>
          {tabs.map(tab => (
            <motion.button
              key={tab}
              whileHover={{ scale: 1.02, transition: { duration: 0.15 } }}
              whileTap={{ scale: 0.97 }}
              onClick={() => setActiveTab(tab)}
              className={`px-5 py-2.5 rounded-xl text-xs font-bold transition-all ${
                activeTab === tab
                  ? 'bg-[#134e40] text-white shadow-md'
                  : 'text-gray-500 hover:text-[#134e40] hover:bg-gray-50'
              }`}
            >
              {tab}
            </motion.button>
          ))}
        </div>

        {/* ── TAB CONTENT ── */}
        <AnimatePresence mode="wait">

          {/* ══ OVERVIEW TAB ══ */}
          {activeTab === 'Overview' && (
            <motion.div
              key="overview"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
              className="grid grid-cols-1 lg:grid-cols-3 gap-5"
            >
              {/* Left 2/3 */}
              <div className="lg:col-span-2 space-y-5">

                {/* Active Escrow Accounts */}
                <div className="bg-white rounded-2xl p-5" style={{ boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}>
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="font-black text-[#1C3627] text-sm flex items-center gap-2 text-left">
                      <Lock size={14} className="text-[#0eb59a]" /> Active Escrow Accounts
                    </h3>
                    <motion.button
                      whileHover={{ scale: 1.05, color: '#134e40' }}
                      whileTap={{ scale: 0.97 }}
                      onClick={() => setShowAddFundsModal(true)}
                      className="flex items-center gap-1.5 text-xs font-bold text-[#0eb59a] hover:text-[#134e40] transition-colors"
                    >
                      <Plus size={12} /> Add Funds
                    </motion.button>
                  </div>

                  <div className="space-y-4">
                    {escrowAccounts.map((account, idx) => (
                      <motion.div
                        key={account.id}
                        initial={{ opacity: 0, x: -12 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: idx * 0.1 }}
                        whileHover={{ y: -3, boxShadow: '0 12px 30px rgba(0,0,0,0.07)', transition: { duration: 0.2 } }}
                        style={{ backgroundColor: '#FAFBF9', borderRadius: '16px', padding: '20px', border: '1px solid #E5E7EB' }}
                      >
                        <div className="flex items-start justify-between mb-4">
                          <div className="flex items-center gap-3">
                            <div className="relative">
                              <img src={account.expertAvatar} className="w-10 h-10 rounded-xl object-cover shadow-sm" />
                              <motion.div
                                animate={{ scale: [1, 1.3, 1] }}
                                transition={{ duration: 2, repeat: Infinity }}
                                className="absolute -bottom-0.5 -right-0.5 w-3 h-3 bg-emerald-500 border-2 border-white rounded-full"
                              />
                            </div>
                            <div className="text-left">
                              <p className="font-black text-[#1C3627] text-sm text-left">{account.engagement}</p>
                              <p className="text-xs text-gray-400 font-medium text-left">with {account.expert}</p>
                            </div>
                          </div>
                          <div className="text-right">
                            <p className="text-xl font-black text-[#134e40] text-right">{account.balance}</p>
                            <p className="text-[10px] text-gray-400 font-medium text-right">in escrow</p>
                          </div>
                        </div>

                        {/* Progress */}
                        <div className="mb-3">
                          <div className="flex justify-between text-[11px] mb-1.5">
                            <span className="text-gray-400 font-semibold text-left">Released: {account.released} of {account.totalValue}</span>
                            <span className="font-black text-[#134e40]">
                              {Math.round((parseInt(account.released.replace(/[₹,]/g, '')) / parseInt(account.totalValue.replace(/[₹,]/g, ''))) * 100)}%
                            </span>
                          </div>
                          <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                            <motion.div
                              initial={{ width: 0 }}
                              animate={{ width: `${Math.round((parseInt(account.released.replace(/[₹,]/g, '')) / parseInt(account.totalValue.replace(/[₹,]/g, ''))) * 100)}%` }}
                              transition={{ duration: 1.2, delay: 0.3 + idx * 0.1 }}
                              className="h-full bg-gradient-to-r from-[#134e40] to-[#0eb59a] rounded-full relative overflow-hidden"
                            >
                              <motion.div
                                animate={{ x: ['-100%', '200%'] }}
                                transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                                className="absolute inset-0 w-1/3 bg-gradient-to-r from-transparent via-white/25 to-transparent"
                              />
                            </motion.div>
                          </div>
                        </div>

                        <div className="flex items-center justify-between">
                          <span className="text-[11px] text-gray-400 font-semibold flex items-center gap-1.5 text-left">
                            <Target size={10} className="text-amber-500" />
                            Next: {account.pendingMilestone}
                          </span>
                          <motion.button
                            whileHover={{ scale: 1.05, boxShadow: '0 6px 15px rgba(14,181,154,0.25)' }}
                            whileTap={{ scale: 0.95 }}
                            onClick={() => setShowReleaseModal(account)}
                            className="text-xs font-black text-[#0eb59a] hover:text-white hover:bg-[#0eb59a] border border-teal-200 bg-teal-50 px-3 py-1.5 rounded-xl transition-all duration-200"
                          >
                            Release Payment →
                          </motion.button>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </div>

                {/* Monthly Spend Chart */}
                <div className="bg-white rounded-2xl p-5" style={{ boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}>
                  <h3 className="font-black text-[#1C3627] text-sm flex items-center gap-2 mb-5 text-left">
                    <BarChart2 size={14} className="text-[#0eb59a]" /> Monthly Spend
                  </h3>
                  <div className="flex items-end gap-3 h-36">
                    {[
                      { month: 'Feb', amount: 350, label: '₹3.5L', active: true },
                      { month: 'Mar', amount: 200, label: '₹2L', active: true },
                      { month: 'Apr', amount: 400, label: '₹4L', active: true },
                      { month: 'May', amount: 0, label: '—', active: false },
                      { month: 'Jun', amount: 0, label: '—', active: false },
                      { month: 'Jul', amount: 0, label: '—', active: false },
                    ].map((bar, idx) => (
                      <motion.div
                        key={bar.month}
                        className="flex-1 flex flex-col items-center gap-2 group cursor-default"
                        whileHover={{ scale: 1.05 }}
                      >
                        <motion.span
                          initial={{ opacity: 0 }}
                          animate={{ opacity: 1 }}
                          transition={{ delay: 0.5 + idx * 0.1 }}
                          className={`text-[10px] font-bold ${bar.active ? 'text-[#134e40]' : 'text-gray-300'}`}
                        >
                          {bar.label}
                        </motion.span>
                        <div className="w-full flex flex-col justify-end" style={{ height: '90px' }}>
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: bar.amount > 0 ? `${(bar.amount / 500) * 90}px` : '6px', opacity: 1 }}
                            transition={{ duration: 0.8, delay: idx * 0.12, ease: 'easeOut' }}
                            whileHover={{ filter: 'brightness(1.1)' }}
                            style={{ borderRadius: '8px 8px 4px 4px' }}
                            className={`w-full ${
                              bar.active
                                ? 'bg-gradient-to-t from-[#134e40] to-[#0eb59a]'
                                : 'bg-gray-100'
                            } transition-all duration-200`}
                          />
                        </div>
                        <span className="text-[10px] font-bold text-gray-400">{bar.month}</span>
                      </motion.div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Right 1/3 */}
              <div className="space-y-4">

                {/* Recent Activity */}
                <div className="bg-white rounded-2xl p-5" style={{ boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}>
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="font-black text-[#1C3627] text-sm flex items-center gap-2 text-left">
                      <Clock size={13} className="text-[#0eb59a]" /> Recent Activity
                    </h3>
                    <motion.button
                      whileHover={{ x: 2 }}
                      onClick={() => setActiveTab('Transactions')}
                      className="text-xs font-bold text-[#0eb59a] hover:text-[#134e40] transition-colors"
                    >
                      View All →
                    </motion.button>
                  </div>
                  <div className="space-y-3">
                    {transactions.slice(0, 4).map((tx, idx) => {
                      const txIcon = getTxIcon(tx.type);
                      return (
                        <motion.div
                          key={tx.id}
                          initial={{ opacity: 0, x: 8 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: idx * 0.07 }}
                          whileHover={{ x: 3, transition: { duration: 0.15 } }}
                          className="flex items-center gap-3 p-2 rounded-xl hover:bg-[#FAFBF9] transition-colors cursor-default"
                        >
                          <div className={`w-8 h-8 ${txIcon.bg} rounded-lg flex items-center justify-center shrink-0`}>
                            <txIcon.icon size={13} className={txIcon.color} />
                          </div>
                          <div className="flex-1 min-w-0 text-left">
                            <p className="text-xs font-bold text-[#1C3627] truncate text-left">{tx.description}</p>
                            <p className="text-[10px] text-gray-400 font-medium text-left">{tx.date}</p>
                          </div>
                          <span className={`text-xs font-black shrink-0 ${tx.amountNum > 0 ? 'text-emerald-600' : 'text-gray-700'}`}>
                            {tx.amount}
                          </span>
                        </motion.div>
                      );
                    })}
                  </div>
                </div>

                {/* Escrow Protection */}
                <motion.div
                  whileHover={{ y: -2, transition: { duration: 0.15 } }}
                  className="bg-gradient-to-br from-[#0d1f2d] to-[#134e40] rounded-2xl p-5 text-white relative overflow-hidden"
                >
                  <div className="absolute -right-4 -top-4 w-20 h-20 bg-white/5 rounded-full pointer-events-none" />
                  <div className="relative z-10">
                    <div className="flex items-center gap-2 mb-2">
                      <div className="w-7 h-7 bg-[#0eb59a]/20 rounded-lg flex items-center justify-center">
                        <Shield size={14} className="text-[#0eb59a]" />
                      </div>
                      <h4 className="font-black text-sm text-left">Escrow Protection</h4>
                    </div>
                    <p className="text-xs text-white/60 leading-relaxed mb-3 text-left">
                      RBI-compliant escrow. Released only when you approve milestones.
                    </p>
                    <div className="space-y-1.5">
                      {['RBI-compliant escrow', 'Instant release on approval', 'Full dispute protection', 'PMO monitoring'].map((item, idx) => (
                        <motion.div
                          key={idx}
                          initial={{ opacity: 0, x: -8 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: 0.2 + idx * 0.07 }}
                          className="flex items-center gap-2 text-xs text-white/70 font-semibold text-left"
                        >
                          <Check size={10} className="text-[#0eb59a] shrink-0" strokeWidth={3} />
                          {item}
                        </motion.div>
                      ))}
                    </div>
                  </div>
                </motion.div>

                {/* Quick Actions */}
                <div className="bg-white rounded-2xl p-5" style={{ boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}>
                  <h3 className="font-black text-[#1C3627] text-sm mb-3 text-left">Quick Actions</h3>
                  <div className="space-y-1">
                    {[
                      { label: 'Add Funds to Escrow', icon: Plus, action: () => setShowAddFundsModal(true), color: 'text-[#0eb59a]', bg: 'bg-teal-50' },
                      { label: 'View Invoices', icon: FileText, action: () => setActiveTab('Invoices'), color: 'text-blue-500', bg: 'bg-blue-50' },
                      { label: 'Download Statement', icon: Download, action: handleDownloadStatement, color: 'text-purple-500', bg: 'bg-purple-50' },
                      { label: 'View Contracts', icon: Lock, action: () => navigate('/contracts'), color: 'text-amber-500', bg: 'bg-amber-50' },
                    ].map((item, idx) => (
                      <motion.button
                        key={idx}
                        whileHover={{ x: 4, backgroundColor: '#FAFBF9', transition: { duration: 0.15 } }}
                        whileTap={{ scale: 0.97 }}
                        onClick={item.action}
                        className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl transition-all group text-left"
                      >
                        <div className={`w-7 h-7 ${item.bg} rounded-lg flex items-center justify-center shrink-0`}>
                          <item.icon size={13} className={item.color} />
                        </div>
                        <span className="text-xs font-bold text-gray-600 group-hover:text-[#134e40] transition-colors flex-1 text-left">{item.label}</span>
                        <ChevronRight size={12} className="text-gray-300 group-hover:text-[#0eb59a] transition-colors" />
                      </motion.button>
                    ))}
                  </div>
                </div>
              </div>
            </motion.div>
          )}

          {/* ══ TRANSACTIONS TAB ══ */}
          {activeTab === 'Transactions' && (
            <motion.div
              key="transactions"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
              className="space-y-4"
            >
              <div className="flex flex-col md:flex-row gap-3">
                <div className="relative flex-1 max-w-sm">
                  <Search size={14} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" />
                  <input
                    type="text"
                    placeholder="Search transactions..."
                    value={searchQuery}
                    onChange={e => setSearchQuery(e.target.value)}
                    className="w-full pl-10 pr-4 py-2.5 bg-white border border-gray-200 rounded-xl text-sm text-left text-gray-700 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#0eb59a]/20 focus:border-[#0eb59a]/40 transition-all"
                    style={{ boxShadow: '0 2px 8px rgba(0,0,0,0.04)' }}
                  />
                </div>
                <div className="flex gap-2">
                  {['All', 'Completed', 'Pending'].map(f => (
                    <motion.button
                      key={f}
                      whileHover={{ scale: 1.04 }}
                      whileTap={{ scale: 0.96 }}
                      onClick={() => setFilterStatus(f)}
                      className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                        filterStatus === f
                          ? 'bg-[#134e40] text-white shadow-md'
                          : 'bg-white text-gray-500 border border-gray-200 hover:border-[#0eb59a]/40 hover:text-[#0eb59a]'
                      }`}
                    >
                      {f}
                    </motion.button>
                  ))}
                </div>
              </div>

              <div className="bg-white rounded-2xl overflow-hidden" style={{ boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}>
                <div className="px-6 py-4 border-b border-gray-50 flex items-center justify-between">
                  <h3 className="font-black text-[#1C3627] text-sm text-left">
                    All Transactions
                    <span className="ml-2 text-xs font-bold text-gray-400 bg-gray-50 px-2 py-0.5 rounded-lg border border-gray-100">
                      {filteredTransactions.length}
                    </span>
                  </h3>
                  <motion.button
                    whileHover={{ scale: 1.05, color: '#0eb59a' }}
                    whileTap={{ scale: 0.97 }}
                    onClick={handleExportCSV}
                    className="flex items-center gap-1.5 text-xs font-bold text-gray-400 hover:text-[#0eb59a] transition-colors"
                  >
                    <Download size={13} /> Export CSV
                  </motion.button>
                </div>

                <div className="divide-y divide-gray-50">
                  {filteredTransactions.map((tx, idx) => {
                    const txIcon = getTxIcon(tx.type);
                    return (
                      <motion.div
                        key={tx.id}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: idx * 0.05 }}
                        whileHover={{ backgroundColor: '#F9FAFB', transition: { duration: 0.15 } }}
                        className="flex items-center gap-4 px-6 py-4 cursor-default"
                      >
                        <div className={`w-9 h-9 ${txIcon.bg} rounded-xl flex items-center justify-center shrink-0`}>
                          <txIcon.icon size={15} className={txIcon.color} />
                        </div>
                        <div className="flex-1 min-w-0 text-left">
                          <p className="font-bold text-[#1C3627] text-sm truncate text-left">{tx.description}</p>
                          <p className="text-xs text-gray-400 font-medium text-left">
                            {tx.engagement} {tx.expert !== '—' ? `· ${tx.expert}` : ''}
                          </p>
                        </div>
                        <div className="text-right shrink-0">
                          <p className={`font-black text-sm text-right ${tx.amountNum > 0 ? 'text-emerald-600' : 'text-[#1C3627]'}`}>
                            {tx.amount}
                          </p>
                          <p className="text-[10px] text-gray-400 font-medium text-right">
                            {tx.date}{tx.time !== '—' ? ` · ${tx.time}` : ''}
                          </p>
                        </div>
                        <div className="shrink-0 flex flex-col items-end gap-1 min-w-[90px]">
                          <span className={`text-[10px] font-black px-2.5 py-1 rounded-lg border ${getStatusStyle(tx.status)}`}>
                            {tx.status}
                          </span>
                          <span className="text-[10px] text-gray-300 font-medium">{tx.txRef}</span>
                        </div>
                      </motion.div>
                    );
                  })}
                </div>
              </div>
            </motion.div>
          )}

          {/* ══ INVOICES TAB ══ */}
          {activeTab === 'Invoices' && (
            <motion.div
              key="invoices"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
              className="space-y-3"
            >
              <div className="flex items-center justify-between">
                <h3 className="font-black text-[#1C3627] text-sm text-left">
                  All Invoices
                  <span className="ml-2 text-xs font-bold text-gray-400">({invoices.length})</span>
                </h3>
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.97 }}
                  onClick={() => {
                    invoices.forEach(inv => handleDownloadInvoice(inv));
                  }}
                  className="flex items-center gap-1.5 text-xs font-bold text-gray-400 hover:text-[#0eb59a] transition-colors"
                >
                  <Download size={13} /> Export All
                </motion.button>
              </div>

              {invoices.map((invoice, idx) => (
                <motion.div
                  key={invoice.id}
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: idx * 0.07 }}
                  whileHover={{ y: -3, boxShadow: '0 12px 30px rgba(0,0,0,0.07)', transition: { duration: 0.2 } }}
                  style={{ boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}
                  className="bg-white rounded-2xl p-5 flex items-center gap-4 group cursor-default"
                >
                  <motion.div
                    whileHover={{ rotate: -5, scale: 1.05 }}
                    className="w-11 h-11 bg-blue-50 rounded-xl flex items-center justify-center shrink-0"
                  >
                    <FileText size={18} className="text-blue-500" />
                  </motion.div>

                  <div className="flex-1 min-w-0 text-left">
                    <div className="flex items-center gap-2 mb-1">
                      <h4 className="font-black text-[#1C3627] text-sm truncate text-left">{invoice.title}</h4>
                      <span className={`text-[10px] font-black px-2 py-0.5 rounded-lg border shrink-0 ${getStatusStyle(invoice.status)}`}>
                        {invoice.status}
                      </span>
                    </div>
                    <div className="flex flex-wrap gap-2 text-[11px] text-gray-400 font-medium text-left">
                      <span className="text-left">{invoice.id}</span>
                      <span>·</span>
                      <span className="flex items-center gap-1 text-left">
                        {invoice.expertAvatar && <img src={invoice.expertAvatar} className="w-3.5 h-3.5 rounded-full object-cover" />}
                        {invoice.expert}
                      </span>
                      <span>·</span>
                      <span className="text-left">{invoice.type}</span>
                      <span>·</span>
                      <span className="flex items-center gap-1 text-left">
                        <Calendar size={9} /> {invoice.date}
                      </span>
                    </div>
                    {invoice.status === 'Pending' && (
                      <p className="text-[10px] text-amber-500 font-bold mt-1 text-left">Due {invoice.dueDate}</p>
                    )}
                  </div>

                  <div className="text-right shrink-0">
                    <p className="font-black text-[#1C3627] text-xl text-right">{invoice.amount}</p>
                  </div>

                  <div className="flex gap-2 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                    <motion.button
                      whileHover={{ scale: 1.1, backgroundColor: '#F0FDF4' }}
                      whileTap={{ scale: 0.9 }}
                      onClick={() => setShowInvoiceModal(invoice)}
                      className="p-2 rounded-xl bg-gray-50 border border-gray-100 text-gray-400 hover:text-[#0eb59a] transition-all"
                    >
                      <Eye size={13} />
                    </motion.button>
                    <motion.button
                      whileHover={{ scale: 1.1, backgroundColor: '#EFF6FF' }}
                      whileTap={{ scale: 0.9 }}
                      onClick={() => handleDownloadInvoice(invoice)}
                      className="p-2 rounded-xl bg-gray-50 border border-gray-100 text-gray-400 hover:text-blue-500 transition-all"
                    >
                      <Download size={13} />
                    </motion.button>
                  </div>
                </motion.div>
              ))}
            </motion.div>
          )}

          {/* ══ ESCROW TAB ══ */}
          {activeTab === 'Escrow' && (
            <motion.div
              key="escrow"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
              className="space-y-5"
            >
              {/* How Escrow Works banner */}
              <div
                className="rounded-2xl p-6 text-white relative overflow-hidden"
                style={{ background: 'linear-gradient(135deg, #0d1f2d, #134e40)' }}
              >
                <div className="absolute -right-8 -top-8 w-40 h-40 bg-white/5 rounded-full pointer-events-none" />
                <div className="absolute -left-4 -bottom-4 w-24 h-24 bg-[#0eb59a]/10 rounded-full pointer-events-none" />
                <div className="relative z-10 flex flex-col md:flex-row md:items-center gap-6">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      <Shield size={18} className="text-[#0eb59a]" />
                      <h3 className="font-black text-base text-left">How Escrow Works</h3>
                    </div>
                    <p className="text-white/60 text-xs leading-relaxed mb-4 text-left">
                      RBI-compliant escrow ensures both parties are protected throughout the engagement.
                    </p>
                    <div className="flex items-center gap-3 flex-wrap">
                      {[
                        { num: '1', label: 'Add Funds' },
                        { num: '2', label: 'Held Securely' },
                        { num: '3', label: 'Approve' },
                        { num: '4', label: 'Expert Paid' },
                      ].map((step, idx, arr) => (
                        <React.Fragment key={step.num}>
                          <div className="flex flex-col items-center gap-1">
                            <motion.div
                              whileHover={{ scale: 1.1 }}
                              className="w-8 h-8 bg-[#0eb59a]/20 border border-[#0eb59a]/30 rounded-full flex items-center justify-center"
                            >
                              <span className="text-[11px] font-black text-[#0eb59a]">{step.num}</span>
                            </motion.div>
                            <span className="text-[10px] font-bold text-white/50">{step.label}</span>
                          </div>
                          {idx < arr.length - 1 && <ChevronRight size={12} className="text-white/20 mb-4" />}
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                  <motion.button
                    whileHover={{ scale: 1.05, boxShadow: '0 8px 25px rgba(14,181,154,0.4)' }}
                    whileTap={{ scale: 0.97 }}
                    onClick={() => setShowAddFundsModal(true)}
                    className="flex items-center gap-2 px-5 py-3 bg-[#0eb59a] hover:bg-[#0ca88e] text-white text-sm font-black rounded-xl transition-all shadow-lg shrink-0"
                  >
                    <Plus size={14} /> Add Funds Now
                  </motion.button>
                </div>
              </div>

              {/* Escrow accounts detail */}
              <div className="space-y-4">
                {escrowAccounts.map((account, idx) => (
                  <motion.div
                    key={account.id}
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: idx * 0.1 }}
                    whileHover={{ y: -3, transition: { duration: 0.2 } }}
                    className="bg-white rounded-2xl p-5"
                    style={{ boxShadow: '0 4px 20px rgba(0,0,0,0.04)' }}
                  >
                    <div className="flex items-center justify-between mb-4">
                      <div className="flex items-center gap-3">
                        <img src={account.expertAvatar} className="w-11 h-11 rounded-xl object-cover shadow-sm" />
                        <div className="text-left">
                          <h4 className="font-black text-[#1C3627] text-sm text-left">{account.engagement}</h4>
                          <p className="text-xs text-gray-400 font-medium text-left">with {account.expert}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="text-2xl font-black text-[#134e40] text-right">{account.balance}</p>
                        <p className="text-[10px] text-gray-400 font-medium text-right">current escrow balance</p>
                      </div>
                    </div>

                    <div className="grid grid-cols-3 gap-3 mb-4">
                      {[
                        { label: 'Total Value', value: account.totalValue, color: 'text-gray-700' },
                        { label: 'Released', value: account.released, color: 'text-emerald-600' },
                        { label: 'In Escrow', value: account.balance, color: 'text-[#134e40]' },
                      ].map((item, iIdx) => (
                        <motion.div
                          key={iIdx}
                          whileHover={{ scale: 1.03, transition: { duration: 0.15 } }}
                          style={{ backgroundColor: '#FAFBF9', borderRadius: '12px', padding: '12px', border: '1px solid #E5E7EB', textAlign: 'center' }}
                        >
                          <p className={`font-black text-sm ${item.color}`}>{item.value}</p>
                          <p className="text-[10px] text-gray-400 font-bold mt-0.5 uppercase tracking-wide">{item.label}</p>
                        </motion.div>
                      ))}
                    </div>

                    <div className="flex gap-3">
                      <motion.button
                        whileHover={{ scale: 1.03, boxShadow: '0 8px 20px rgba(16,185,129,0.25)' }}
                        whileTap={{ scale: 0.97 }}
                        onClick={() => setShowReleaseModal(account)}
                        className="flex-1 flex items-center justify-center gap-2 py-2.5 bg-emerald-500 hover:bg-emerald-600 text-white text-sm font-black rounded-xl shadow-md transition-all"
                      >
                        <Unlock size={14} /> Release Milestone Payment
                      </motion.button>
                      <motion.button
                        whileHover={{ scale: 1.03, backgroundColor: '#F0FDF4', borderColor: '#0eb59a' }}
                        whileTap={{ scale: 0.97 }}
                        onClick={() => setShowAddFundsModal(true)}
                        className="flex items-center justify-center gap-2 px-5 py-2.5 bg-white border border-gray-200 text-gray-600 text-sm font-black rounded-xl hover:text-[#0eb59a] transition-all"
                      >
                        <Plus size={14} /> Top Up
                      </motion.button>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}

        </AnimatePresence>
      </div>
    </div>

    {/* ══ ADD FUNDS MODAL ══ */}
    <AnimatePresence>
      {showAddFundsModal && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={() => { setShowAddFundsModal(false); setSelectedAmount(''); setCustomAmount(''); }}
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-md p-4"
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 24 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 24 }}
            transition={{ type: 'spring', stiffness: 300, damping: 25 }}
            onClick={e => e.stopPropagation()}
            className="bg-white rounded-3xl shadow-2xl max-w-md w-full overflow-hidden"
          >
            <AnimatePresence mode="wait">
              {!addFundsSent ? (
                <motion.div key="form" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>

                  {/* Gradient header */}
                  <div style={{ background: 'linear-gradient(135deg, #134e40, #0eb59a)', padding: '24px' }}>
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <div className="w-8 h-8 bg-white/20 rounded-lg flex items-center justify-center">
                          <Plus size={16} className="text-white" />
                        </div>
                        <div>
                          <h3 className="font-black text-white text-base text-left">Add Funds to Escrow</h3>
                          <p className="text-white/70 text-xs text-left">Secured immediately on transfer</p>
                        </div>
                      </div>
                      <motion.button
                        whileHover={{ scale: 1.1, rotate: 90 }}
                        whileTap={{ scale: 0.9 }}
                        onClick={() => { setShowAddFundsModal(false); setSelectedAmount(''); setCustomAmount(''); }}
                        className="w-7 h-7 bg-white/20 rounded-lg flex items-center justify-center text-white hover:bg-white/30 transition-all"
                      >
                        <X size={13} />
                      </motion.button>
                    </div>

                    {/* Current balance display */}
                    <div className="bg-white/10 rounded-xl p-3 mt-3 flex items-center justify-between">
                      <span className="text-white/70 text-xs font-semibold text-left">Current Escrow Balance</span>
                      <span className="text-white font-black text-sm">{escrowSummary.totalBalance}</span>
                    </div>
                  </div>

                  {/* Body */}
                  <div className="p-6">
                    {/* Quick amounts */}
                    <div className="mb-5">
                      <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-3 text-left">
                        Select Amount
                      </label>
                      <div className="grid grid-cols-2 gap-2 mb-3">
                        {quickAmounts.map(amount => (
                          <motion.button
                            key={amount}
                            whileHover={{ scale: 1.03 }}
                            whileTap={{ scale: 0.97 }}
                            onClick={() => { setSelectedAmount(amount); setCustomAmount(''); }}
                            className={`py-3 rounded-xl text-sm font-black border-2 transition-all ${
                              selectedAmount === amount
                                ? 'border-[#0eb59a] bg-teal-50 text-[#134e40]'
                                : 'border-gray-100 bg-gray-50 text-gray-600 hover:border-gray-200'
                            }`}
                          >
                            {amount}
                          </motion.button>
                        ))}
                      </div>
                      <div className="relative">
                        <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400 font-bold text-sm">₹</span>
                        <input
                          type="text"
                          placeholder="Custom amount..."
                          value={customAmount}
                          onChange={e => { setCustomAmount(e.target.value); setSelectedAmount(''); }}
                          className="w-full pl-8 pr-4 py-3 bg-gray-50 border-2 border-gray-100 rounded-xl text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-[#0eb59a]/20 focus:border-[#0eb59a]/40 transition-all text-left"
                          onFocus={e => e.target.style.borderColor = '#0eb59a'}
                          onBlur={e => e.target.style.borderColor = customAmount ? '#0eb59a' : '#F3F4F6'}
                        />
                      </div>
                    </div>

                    {/* Payment method */}
                    <div className="mb-5">
                      <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-3 text-left">
                        Payment Method
                      </label>
                      <div className="space-y-2">
                        {paymentMethods.map(method => (
                          <motion.button
                            key={method.id}
                            whileHover={{ x: 3, transition: { duration: 0.15 } }}
                            whileTap={{ scale: 0.98 }}
                            onClick={() => setPaymentMethod(method.id)}
                            className={`w-full flex items-center gap-3 p-3 rounded-xl border-2 transition-all text-left ${
                              paymentMethod === method.id
                                ? 'border-[#0eb59a] bg-teal-50'
                                : 'border-gray-100 bg-gray-50 hover:border-gray-200'
                            }`}
                          >
                            <span className="text-lg shrink-0">{method.icon}</span>
                            <div className="flex-1 text-left">
                              <p className={`text-sm font-black text-left ${paymentMethod === method.id ? 'text-[#134e40]' : 'text-gray-700'}`}>
                                {method.label}
                              </p>
                              <p className="text-xs text-gray-400 font-medium text-left">{method.desc}</p>
                            </div>
                            {paymentMethod === method.id && (
                              <motion.div
                                initial={{ scale: 0 }}
                                animate={{ scale: 1 }}
                                className="w-5 h-5 bg-[#0eb59a] rounded-full flex items-center justify-center shrink-0"
                              >
                                <Check size={10} className="text-white" strokeWidth={3} />
                              </motion.div>
                            )}
                          </motion.button>
                        ))}
                      </div>
                    </div>

                    {/* Security notice */}
                    <div className="flex items-start gap-2 p-3 bg-teal-50 rounded-xl border border-teal-100 mb-5">
                      <Shield size={13} className="text-[#0eb59a] shrink-0 mt-0.5" />
                      <p className="text-[11px] text-teal-700 leading-relaxed text-left">
                        Funds transferred to an RBI-compliant escrow. You retain full control and can request refunds for unused balances.
                      </p>
                    </div>

                    <div className="flex gap-3">
                      <motion.button
                        whileHover={{ scale: 1.02, backgroundColor: '#F3F4F6' }}
                        whileTap={{ scale: 0.98 }}
                        onClick={() => { setShowAddFundsModal(false); setSelectedAmount(''); setCustomAmount(''); }}
                        className="flex-1 py-3 bg-gray-50 border border-gray-200 text-gray-600 text-sm font-bold rounded-2xl transition-all"
                      >
                        Cancel
                      </motion.button>
                      <motion.button
                        whileHover={{ scale: (selectedAmount || customAmount) ? 1.02 : 1, boxShadow: (selectedAmount || customAmount) ? '0 8px 25px rgba(20,78,64,0.3)' : 'none' }}
                        whileTap={{ scale: (selectedAmount || customAmount) ? 0.98 : 1 }}
                        disabled={!selectedAmount && !customAmount}
                        onClick={handleAddFunds}
                        style={{
                          flex: 1,
                          padding: '12px',
                          background: (selectedAmount || customAmount) ? 'linear-gradient(135deg, #134e40, #0eb59a)' : '#F3F4F6',
                          color: (selectedAmount || customAmount) ? 'white' : '#9CA3AF',
                          border: 'none',
                          borderRadius: '16px',
                          fontSize: '14px',
                          fontWeight: 800,
                          cursor: (selectedAmount || customAmount) ? 'pointer' : 'not-allowed',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          gap: '6px',
                        }}
                      >
                        <Zap size={14} fill={(selectedAmount || customAmount) ? 'currentColor' : 'none'} />
                        Add {selectedAmount || (customAmount ? `₹${customAmount}` : 'Funds')}
                      </motion.button>
                    </div>
                  </div>
                </motion.div>
              ) : (
                <motion.div
                  key="success"
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="text-center py-12 px-8"
                >
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: 'spring', stiffness: 300, damping: 20, delay: 0.1 }}
                    style={{
                      width: '80px', height: '80px',
                      background: 'linear-gradient(135deg, #134e40, #0eb59a)',
                      borderRadius: '50%',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      margin: '0 auto 20px',
                      boxShadow: '0 12px 40px rgba(14,181,154,0.3)',
                    }}
                  >
                    <Check size={36} color="white" strokeWidth={3} />
                  </motion.div>
                  <h3 className="text-xl font-black text-[#1C3627] mb-2">Funds Added!</h3>
                  <p className="text-sm text-gray-500 leading-relaxed">
                    {selectedAmount || `₹${customAmount}`} has been added to your escrow and is ready for milestone releases.
                  </p>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>

    {/* ══ RELEASE PAYMENT MODAL ══ */}
    <AnimatePresence>
      {showReleaseModal && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={() => setShowReleaseModal(null)}
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-md p-4"
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 24 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 24 }}
            transition={{ type: 'spring', stiffness: 300, damping: 25 }}
            onClick={e => e.stopPropagation()}
            className="bg-white rounded-3xl shadow-2xl max-w-sm w-full overflow-hidden"
          >
            <AnimatePresence mode="wait">
              {!releaseSent ? (
                <motion.div key="form" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>

                  {/* Gradient header */}
                  <div style={{ background: 'linear-gradient(135deg, #065f46, #059669)', padding: '24px', textAlign: 'center' }}>
                    <motion.div
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      transition={{ type: 'spring', stiffness: 300, damping: 20 }}
                      className="w-16 h-16 bg-white/20 rounded-2xl flex items-center justify-center mx-auto mb-3"
                    >
                      <Unlock size={28} className="text-white" />
                    </motion.div>
                    <h3 className="text-lg font-black text-white">Release Payment</h3>
                    <p className="text-white/70 text-xs mt-1">
                      {showReleaseModal.engagement}
                    </p>
                  </div>

                  <div className="p-6">
                    {/* Amount display */}
                    <div className="bg-emerald-50 rounded-2xl p-5 border border-emerald-100 text-center mb-5">
                      <p className="text-[10px] font-black text-emerald-600 uppercase tracking-widest mb-1">Releasing to {showReleaseModal.expert}</p>
                      <p className="text-4xl font-black text-emerald-700">{showReleaseModal.balance}</p>
                    </div>

                    <div className="space-y-2 text-xs mb-5">
                      {[
                        { label: 'Milestone', value: showReleaseModal.pendingMilestone },
                        { label: 'Expert', value: showReleaseModal.expert },
                        { label: 'Estimated arrival', value: 'Within 24 hours' },
                      ].map((item, idx) => (
                        <div key={idx} className="flex justify-between py-1.5 border-b border-gray-50 last:border-0">
                          <span className="text-gray-400 font-semibold text-left">{item.label}</span>
                          <span className={`font-bold text-right ${item.label === 'Estimated arrival' ? 'text-emerald-600' : 'text-[#1C3627]'}`}>
                            {item.value}
                          </span>
                        </div>
                      ))}
                    </div>

                    <div className="flex gap-3">
                      <motion.button
                        whileHover={{ scale: 1.02, backgroundColor: '#F3F4F6' }}
                        whileTap={{ scale: 0.98 }}
                        onClick={() => setShowReleaseModal(null)}
                        className="flex-1 py-3 bg-gray-50 border border-gray-200 text-gray-600 text-sm font-bold rounded-2xl transition-all"
                      >
                        Cancel
                      </motion.button>
                      <motion.button
                        whileHover={{ scale: 1.03, boxShadow: '0 8px 25px rgba(16,185,129,0.35)' }}
                        whileTap={{ scale: 0.97 }}
                        onClick={handleRelease}
                        className="flex-1 py-3 bg-emerald-500 hover:bg-emerald-600 text-white text-sm font-black rounded-2xl shadow-md transition-all flex items-center justify-center gap-2"
                      >
                        <Unlock size={14} /> Confirm Release
                      </motion.button>
                    </div>
                  </div>
                </motion.div>
              ) : (
                <motion.div
                  key="success"
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="text-center py-12 px-8"
                >
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: 'spring', stiffness: 300, damping: 20, delay: 0.1 }}
                    style={{
                      width: '80px', height: '80px',
                      background: 'linear-gradient(135deg, #065f46, #059669)',
                      borderRadius: '50%',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      margin: '0 auto 20px',
                      boxShadow: '0 12px 40px rgba(16,185,129,0.3)',
                    }}
                  >
                    <Check size={36} color="white" strokeWidth={3} />
                  </motion.div>
                  <h3 className="text-xl font-black text-[#1C3627] mb-2">Payment Released!</h3>
                  <p className="text-sm text-gray-500 leading-relaxed">
                    {showReleaseModal?.balance} will be transferred to {showReleaseModal?.expert} within 24 hours.
                  </p>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>

    {/* ══ INVOICE MODAL ══ */}
    <AnimatePresence>
      {showInvoiceModal && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={() => setShowInvoiceModal(null)}
          className="fixed inset-0 z-55 flex items-center justify-center bg-black/40 backdrop-blur-md p-4"
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.93, y: 24 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.93, y: 24 }}
            transition={{ type: 'spring', stiffness: 300, damping: 25 }}
            onClick={e => e.stopPropagation()}
            className="bg-white rounded-3xl shadow-2xl max-w-md w-full overflow-hidden"
          >
            {/* Gradient header */}
            <div style={{ background: 'linear-gradient(135deg, #1e3a5f, #1d4ed8)', padding: '24px' }}>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-blue-200 text-[10px] font-black uppercase tracking-widest text-left">Invoice</p>
                  <h3 className="text-white font-black text-lg text-left">{showInvoiceModal.id}</h3>
                  <p className="text-blue-200 text-xs text-left">{showInvoiceModal.type}</p>
                </div>
                <div className="flex items-center gap-2">
                  <motion.button
                    whileHover={{ scale: 1.05, backgroundColor: 'rgba(255,255,255,0.2)' }}
                    whileTap={{ scale: 0.95 }}
                    onClick={() => handleDownloadInvoice(showInvoiceModal)}
                    className="flex items-center gap-1.5 px-3 py-2 bg-white/10 border border-white/20 text-white text-xs font-bold rounded-xl transition-all"
                  >
                    <Download size={12} /> Download
                  </motion.button>
                  <motion.button
                    whileHover={{ scale: 1.1, rotate: 90 }}
                    whileTap={{ scale: 0.9 }}
                    onClick={() => setShowInvoiceModal(null)}
                    className="w-8 h-8 bg-white/10 rounded-xl flex items-center justify-center text-white hover:bg-white/20 transition-all"
                  >
                    <X size={15} />
                  </motion.button>
                </div>
              </div>
            </div>

            <div className="p-6">
              <div className="bg-[#FAFBF9] rounded-xl border border-gray-100 p-4 mb-5 space-y-3">
                {[
                  { label: 'Description', value: showInvoiceModal.title },
                  { label: 'Expert', value: showInvoiceModal.expert },
                  { label: 'Engagement', value: showInvoiceModal.engagement },
                  { label: 'Invoice Date', value: showInvoiceModal.date },
                  { label: 'Due Date', value: showInvoiceModal.dueDate },
                ].map((item, idx) => (
                  <div key={idx} className={`flex justify-between text-xs py-1.5 ${idx < 4 ? 'border-b border-gray-100' : ''}`}>
                    <span className="text-gray-400 font-semibold text-left">{item.label}</span>
                    <span className="font-bold text-[#1C3627] text-right max-w-[60%]">{item.value}</span>
                  </div>
                ))}
                <div className="flex justify-between pt-2">
                  <span className="font-black text-[#1C3627] text-sm">Total Amount</span>
                  <span className="font-black text-2xl text-[#134e40]">{showInvoiceModal.amount}</span>
                </div>
              </div>

              <div className="flex items-center gap-3 mb-5">
                <span className={`inline-flex items-center gap-1.5 text-xs font-black px-3 py-1.5 rounded-xl border ${getStatusStyle(showInvoiceModal.status)}`}>
                  {showInvoiceModal.status === 'Paid' ? <Check size={11} strokeWidth={3} /> : <Clock size={11} />}
                  {showInvoiceModal.status}
                </span>
                {showInvoiceModal.status === 'Pending' && (
                  <span className="text-xs text-amber-500 font-bold">Due {showInvoiceModal.dueDate}</span>
                )}
              </div>

              <div className="flex gap-3">
                <motion.button
                  whileHover={{ scale: 1.02, backgroundColor: '#F3F4F6' }}
                  whileTap={{ scale: 0.98 }}
                  onClick={() => setShowInvoiceModal(null)}
                  className="flex-1 py-3 bg-gray-50 border border-gray-200 text-gray-600 text-sm font-bold rounded-2xl transition-all"
                >
                  Close
                </motion.button>
                <motion.button
                  whileHover={{ scale: 1.02, boxShadow: '0 8px 20px rgba(29,78,216,0.25)' }}
                  whileTap={{ scale: 0.98 }}
                  onClick={() => handleDownloadInvoice(showInvoiceModal)}
                  className="flex-1 py-3 bg-blue-600 hover:bg-blue-700 text-white text-sm font-black rounded-2xl shadow-md transition-all flex items-center justify-center gap-2"
                >
                  <Download size={14} /> Download PDF
                </motion.button>
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>

  </div>
);
};

export default Payments;
